# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - lifecycle/frozen

# Set to true to ignore issues in a project
exemptProjects: true

# Set to true to ignore issues in a milestone
exemptMilestones: true

# Label to use when marking an issue as stale
staleLabel: lifecycle/stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: |
  This issue has been automatically marked as stale because it has not had activity in __60 days__.
  It will be closed in __7 days__ if no further activity occurs.
  
  Thank you for your contributions.
  
  ---
  
  Issues never become stale if any of the following is true:
  
  1. they are added to a __Project__
  2. they are added to a __Milestone__
  3. they have the `lifecycle/frozen` label

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false