{{- if .Values.airflow.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-sync-users
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: sync-users
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  sync_users.py: |-
    {{- include "airflow.snyc.sync_users.py" . | indent 4 }}
{{- end }}