{{- if .Values.airflow.connections }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-sync-connections
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: sync-connections
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  sync_connections.py: |-
    {{- include "airflow.snyc.sync_connections.py" . | indent 4 }}
{{- end }}