{{- if .Values.airflow.pools }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-sync-pools
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: sync-pools
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  sync_pools.py: |-
    {{- include "airflow.snyc.sync_pools.py" . | indent 4 }}
{{- end }}