{{- if .Values.dags.controlled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-sync-dags
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: sync-dags
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  sync_variables.py: {{ include "airflow.sync.sync_dags.py" . | b64enc | quote }}
{{- end }}