{{- if not .Values.web.webserverConfig.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-webserver-config
  labels:
    app: {{ include "airflow.labels.app" . }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  webserver_config.py: |-
    {{- if .Values.web.webserverConfig.stringOverride }}
    {{- .Values.web.webserverConfig.stringOverride | nindent 4 }}
    {{- else }}
    {{- tpl (.Files.Get "files/webserver_config.py") . | nindent 4 }}
    {{- end }}
{{- end }}