{{- if .Values.dags.gitSync.enabled }}
{{- range .Values.dags.gitSync.repositories }}
{{- $repo := mergeOverwrite . (deepCopy $.Values.dags.gitSync.repository) (deepCopy . )}}
{{- $name := include "airflow.repo.name" . -}}
{{- if and .enabled .sshKnownHosts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" $ }}-{{ $name }}-known-hosts
  labels:
    app: {{ include "airflow.labels.app" $ }}
    chart: {{ include "airflow.labels.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  known_hosts: {{ .sshKnownHosts | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
