{{- if and (.Values.dags.sync.enabled) (.Values.dags.sync.git.sshKnownHosts) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-known-hosts
  labels:
    app: {{ include "airflow.labels.app" . }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  known_hosts: {{ .Values.dags.sync.git.sshKnownHosts | b64enc | quote }}
{{- end }}
