{{- if not .Values.scheduler.existingSecretConnections }}
{{- if .Values.scheduler.connections }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-connections
  labels:
    app: {{ include "airflow.labels.app" . }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  add-connections.sh: |
    #!/usr/bin/env bash
    {{- range .Values.scheduler.connections }}
    {{- if $.Values.scheduler.refreshConnections }}
    airflow connections --delete --conn_id {{ .id | quote | replace `$` `\$` }}
    {{- end }}
    airflow connections --add --conn_id {{ .id | quote | replace `$` `\$` }}
    {{- if .type }} --conn_type {{ .type | quote | replace `$` `\$` }} {{ end -}}
    {{- if .uri }} --conn_uri {{ .uri | quote | replace `$` `\$` }} {{ end -}}
    {{- if .host }} --conn_host {{ .host | quote | replace `$` `\$` }} {{ end -}}
    {{- if .login }} --conn_login {{ .login | quote | replace `$` `\$` }} {{ end -}}
    {{- if .password }} --conn_password {{ .password | quote | replace `$` `\$` }} {{ end -}}
    {{- if .schema }} --conn_schema {{ .schema | quote | replace `$` `\$` }} {{ end -}}
    {{- if .port }} --conn_port {{ .port | quote | replace `$` `\$` }} {{ end -}}
    {{- if .extra }} --conn_extra {{ ( regexReplaceAll "[\r\n]+" .extra "" ) | quote | replace `$` `\$` }} {{ end -}}
    {{- end }}
{{- end }}
{{- end }}
