# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: airflow-eks-staging
  region: us-west-2

vpc:
  id: "vpc-d5f0ebb1"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16"       # (optional, must match CIDR used by the given VPC)
  securityGroup: "sg-9c54b1ec"
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      us-west-2b:
        id: "subnet-0714698ebd47eff4e"
        cidr: "172.31.48.0/20"

      us-west-2c:
        id: "subnet-074fc8e89887e1128"
        cidr: "172.31.64.0/20"

      us-west-2a:
        id: "subnet-090900e18339d52ad"
        cidr: "172.31.80.0/20"