{{- $any_client_needed :=  or (not .Values.pgbouncer.clientSSL.caFile.existingSecret) (not .Values.pgbouncer.clientSSL.keyFile.existingSecret) (not .Values.pgbouncer.clientSSL.certFile.existingSecret) }}
{{- $any_server_needed :=  or (not .Values.pgbouncer.serverSSL.caFile.existingSecret) (not .Values.pgbouncer.serverSSL.keyFile.existingSecret) (not .Values.pgbouncer.serverSSL.certFile.existingSecret) }}
{{- if and (include "airflow.pgbouncer.should_use" .) (or $any_client_needed $any_server_needed) }}
{{- $client_ca := genCA "client-ca" 365 }}
{{- $client_cert := genSignedCert "localhost" nil nil 365 $client_ca }}
{{- $server_ca := genCA "server-ca" 365 }}
{{- $server_cert := genSignedCert "localhost" nil nil 365 $server_ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-pgbouncer-certs
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: pgbouncer
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if not .Values.pgbouncer.clientSSL.caFile.existingSecret }}
  client-ca.crt: {{ $client_ca.Cert | b64enc | quote }}
  {{- end }}
  {{- if not .Values.pgbouncer.clientSSL.keyFile.existingSecret }}
  client.key: {{ $client_cert.Key | b64enc | quote }}
  {{- end }}
  {{- if not .Values.pgbouncer.clientSSL.certFile.existingSecret }}
  client.crt: {{ $client_cert.Cert  | b64enc | quote }}
  {{- end }}

  {{- if not .Values.pgbouncer.serverSSL.caFile.existingSecret }}
  server-ca.crt: {{ $server_ca.Cert | b64enc | quote }}
  {{- end }}
  {{- if not .Values.pgbouncer.serverSSL.keyFile.existingSecret }}
  server.key: {{ $server_cert.Key | b64enc | quote }}
  {{- end }}
  {{- if not .Values.pgbouncer.serverSSL.certFile.existingSecret }}
  server.crt: {{ $server_cert.Cert | b64enc | quote }}
  {{- end }}
{{- end }}