{{- if include "airflow.pgbouncer.should_use" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-pgbouncer
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: pgbouncer
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pgbouncer.ini: {{ include "airflow.pgbouncer.pgbouncer.ini" . | b64enc | quote }}
  gen_auth_file.sh: {{ include "airflow.pgbouncer.gen_auth_file.sh" . | b64enc | quote }}
  {{- if or (not .Values.pgbouncer.clientSSL.keyFile.existingSecret) (not .Values.pgbouncer.clientSSL.certFile.existingSecret) }}
  gen_self_signed_cert.sh: {{ include "airflow.pgbouncer.gen_self_signed_cert.sh" . | b64enc | quote }}
  {{- end }}
{{- end }}