{{- if and (.Values.workers.enabled) (include "airflow.executor.celery_like" .) }}
apiVersion: v1
## Service gives stable DNS entries for workers, used by webserver for logs
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: worker
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: worker
      protocol: TCP
      port: 8793
  clusterIP: None
  selector:
    app: {{ include "airflow.labels.app" . }}
    component: worker
{{- end }}
