name: "Pgbouncer | Run Tests"

on:
  pull_request:
    branches:
      - main
    paths:
      - "images/pgbouncer/**"

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate Image Tags/Labels
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            airflowhelm/charts
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./images/pgbouncer
          push: false
          platforms: |
            linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
