name: "Pgbouncer | Run Tests"

on:
  pull_request:
    branches:
      - main
    paths:
      - "images/pgbouncer/**"

jobs:
  build-container-image:
    uses: ./.github/workflows/build-container-image.yaml
    with:
      platforms: |
        linux/amd64
