apiVersion: v1
kind: Secret
metadata:
  name: add-airflow-connections
type: Opaque
stringData:
  add-connections.sh: |
    #!/usr/bin/env bash
    airflow connections --delete --conn_id "snowflake_conn"
    airflow connections --delete --conn_id "aws_default"
    airflow connections --delete --conn_id "postgres_master"
    airflow connections --delete --conn_id "shopify_http_conn"
    airflow connections --delete --conn_id "slack"

    airflow connections --add --conn_id 'SNOWFLAKE_CONN' --conn_uri 'snowflake://<user>:<password>@https%3A%2F%2F<account>.snowflakecomputing.com%2F/<schema>?account=<account>&warehouse=<warehouse>&database=<database>&region=us-west-2&role=<role>'
    airflow connections --add --conn_id 'AWS_DEFAULT' --conn_uri 'aws://<pwd>:<secret key>@?aws_iam_role=<aws_iam_role>&region_name=us-west-2'
    airflow connections --add --conn_id 'POSTGRES_MASTER' --conn_uri 'postgresql://<user>:<pwd>@<host>:5432/<db>'
    airflow connections --add --conn_id 'SHOPIFY_HTTP_CONN' --conn_uri 'http:///https'
    airflow connections --add --conn_id 'SLACK' --conn_uri '<web hook token>'